services:
  - docker
install: true
script:
 - cp docker-compose.env.sample docker-compose.env
 - docker-compose --file docker-compose.test.yml build
 - docker-compose --file docker-compose.test.yml up -d db-test
 - docker-compose --file docker-compose.test.yml up -d elasticsearch-test
 - docker-compose --file docker-compose.test.yml run test rake
 - docker-compose --file docker-compose.test.yml down
