common_caps:
  "browserstack.debug": true
  "browserstack.local": true
  "build": "rspec-browserstack"
  "project": "TeachingJobs"

browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"
  -
    "browser": "safari"
  -
    "browser": "IE"
    "browser_version": "10.0"
  -
    "browser": "edge"
